version: '3'
services:
  eia-server:
    container_name: eia-server
    image: eia-server:latest
    environment:
      - PYTHONUNBUFFERED=1
    # networks:
    #   - eia_network
    entrypoint: /main.py

  eia-ui:
    container_name: eia-ui
    build:
      context: ./backoffice/eia-ui
      dockerfile: Dockerfile
    image: eia-ui:latest
    volumes:
      - './backoffice/eia-ui:/app'
      - '/app/node_modules'

    ports:
      - 3333:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

# networks:
#   default:
#     external:
#       name: eia_network