version: '3'
services:

  eia_api:
    container_name: eia_api
    image: eia_api
    expose:
      - 8080
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LISTENING_PORT=8080
    entrypoint: /main.py

  swagger:
    image: swaggerapi/swagger-ui
    expose:
      - 8080
    ports:
      - 8029:8080
    environment:
      SWAGGER_JSON: /spec/swagger.yaml
    volumes:
      - ./spec:/spec
