version: '3'
services:

  swagger:
    image: swaggerapi/swagger-ui
    expose:
      - 8080
    ports:
      - 8029:8080
    environment:
      SWAGGER_JSON: /spec/swagger.yaml
    volumes:
      - ./spec:/spec
